# Ndarray对象

练习1

In [1]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

练习2

In [3]:
# 对于一个维度
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

练习3

In [4]:
# 最小纬度
c = np.array([1,2,3,4,5],ndmin = 2)
c

array([[1, 2, 3, 4, 5]])

练习4

In [5]:
# dtype参数
d = np.array([1,2,3],dtype = complex)
d

array([1.+0.j, 2.+0.j, 3.+0.j])

# 创建数组

numpy.empty 方法用来创建一个指定形状（shape）、数据类型（dtype）且未初始化的数组：

> numpy.empty(shape, dtype = float, order = 'C')

参数说明：

|参数	|描述|
|----|----|
|shape	|数组形状|
|dtype	|数据类型，可选|
|order	|有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。|

In [12]:
import numpy as np
x = np.empty([3,2], dtype = int)
x

array([[0, 0],
       [0, 0],
       [0, 0]])

### numpy.zeros

创建指定大小的数组，数组元素以 0 来填充：


numpy.zeros(shape, dtype = float, order = 'C')


参数	描述

shape	数组形状

dtype	数据类型，可选

order	'C' 用于 C 的行数组，或者 'F' 用于 FORTRAN 的列数组

In [13]:
import numpy as np  
# 默认为浮点数 
x = np.zeros(5)
print(x)  

[0. 0. 0. 0. 0.]


In [14]:
# 设置类型为整数 
y = np.zeros((5,), dtype = np.int)
print(y)  

[0 0 0 0 0]


In [15]:
# 自定义类型
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])
print(z)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


### numpy.ones
创建指定形状的数组，数组元素以 1 来填充：

numpy.ones(shape, dtype = None, order = 'C')

参数	描述

shape	数组形状

dtype	数据类型，可选

order	'C' 用于 C 的行数组，或者 'F' 用于 FORTRAN 的列数组

In [16]:
# 默认为浮点数 
x = np.ones(5)  
print(x)  

[1. 1. 1. 1. 1.]


In [17]:
# 自定义类型 
x = np.ones([2,2], dtype = int)
print(x)

[[1 1]
 [1 1]]
