### Numpy由c语言编写，消耗资源少，性能高

In [1]:
# 安装 直接使用anaconda

In [2]:
# 导入模块
import numpy as np

In [4]:
# 创建一个矩阵
array = np.array([[1,2,3],[4,5,6]])
print(array)
type(array)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [5]:
array.ndim  # 维度

2

In [7]:
array.shape  # 大小形状（2行3列）

(2, 3)

In [8]:
array.size  # 元素个数

6

In [11]:
# 指定类型
a = np.array([2,3,4],dtype = np.int)
print(a.dtype)

int32


In [12]:
a = np.array([2,3,4],dtype=np.float32)
print(a.dtype)

float32


In [16]:
# 默认为0,3行4列
a = np.zeros((3,4),dtype = np.int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
# 默认为1,3行3列
a = np.ones((3,3),dtype=np.int)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
a = np.empty((3,4))
a  # 这里是内存上是多少就是多少

array([[1.23983762e-311, 2.81617418e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.33664410e+160, 7.48251912e-091,
        1.79616208e-052],
       [2.81261915e-033, 5.40758150e-066, 6.48224659e+170,
        4.93432906e+257]])

In [18]:
# 创建连续数组
a = np.arange(10,20,2)
a

array([10, 12, 14, 16, 18])

In [20]:
# 连续3行4列
a = np.arange(12)
a.reshape((3,4))


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
# 1到10，20个数
a = np.linspace(1,10,20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])