In [1]:
import numpy as np

In [2]:
a = np.array([0,30,35,60,90])

In [4]:
# 根据度数转化成正弦值
np.sin(a*np.pi/180)

array([0.        , 0.5       , 0.57357644, 0.8660254 , 1.        ])

In [5]:
# 根据度数转化成余弦值
np.cos(a*np.pi/180)

array([1.00000000e+00, 8.66025404e-01, 8.19152044e-01, 5.00000000e-01,
       6.12323400e-17])

In [6]:
# 正切值
np.tan(a*np.pi/180)

array([0.00000000e+00, 5.77350269e-01, 7.00207538e-01, 1.73205081e+00,
       1.63312394e+16])

In [7]:
# 舍入
# numpy.around(数组，位数)
a = np.array([1.056,525,640.222,63])
np.around(a,2)

array([  1.06, 525.  , 640.22,  63.  ])

In [9]:
# 向下取整
np.floor(a)

array([  1., 525., 640.,  63.])

In [10]:
# 向上取整
np.ceil(a)

array([  2., 525., 641.,  63.])