In [1]:
# 按轴进行获取最大最小值
import numpy as np

In [2]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [3]:
np.amin(a,1)  # 1代表按行取最小值，0代表按列组最小值

array([3, 3, 2])

In [4]:
np.amax(a,0)

array([8, 7, 9])

### numpy.ptp
最大啊最小的差距

In [5]:
np.ptp(a)

7

In [6]:
# 按照轴最大最小的差
np.ptp(a,0)

array([6, 3, 6])

In [8]:
# 百分位数
a = np.array([[10,7,4],[3,2,1]])
np.percentile(a,50)  #中位数

3.5

In [9]:
# 按照轴计算中位数
np.percentile(a,50,axis=1)  # 水平

array([7., 2.])

In [11]:
# 按照轴计算中位数
np.percentile(a,50,axis=0)  # 列

array([6.5, 4.5, 2.5])

In [12]:
np.median(a,axis=0)

array([6.5, 4.5, 2.5])

In [13]:
# 算术平均值
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.mean(a)

5.0

In [16]:
# 按轴计算平均值
np.mean(a,axis=0)

array([4., 5., 6.])

In [17]:
# 标准差
np.std(a)

2.581988897471611

In [18]:
# 方差
np.var(a)

6.666666666666667