In [2]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
np.save('outfile.npy',a)

In [5]:
# 从文件中读取数据
b = np.load('outfile.npy')
b

array([1, 2, 3, 4])

In [9]:
# np.savez()可以将多个数组保存到文件
a = np.array([[1,2,3],[5,6,8]])
b = np.array([5,6,8])
c = np.arange(0,1,4.5)

np.savez('lichee.npz',a,b,c)

In [10]:
d = np.load('lichee.npz')
d.files

['arr_0', 'arr_1', 'arr_2']

In [12]:
d['arr_0']

array([[1, 2, 3],
       [5, 6, 8]])

In [13]:
# 以文本的形式存放
e = np.array([1,2,3,4,5,6])
np.savetxt('out.txt',a)

In [15]:
f = np.loadtxt('out.txt')
f

array([[1., 2., 3.],
       [5., 6., 8.]])

['C:\\Users\\那年\\Desktop\\study\\数据分析\\pandas', 'F:\\py\\Anaconda3\\python37.zip', 'F:\\py\\Anaconda3\\DLLs', 'F:\\py\\Anaconda3\\lib', 'F:\\py\\Anaconda3', '', 'C:\\Users\\那年\\AppData\\Roaming\\Python\\Python37\\site-packages', 'F:\\py\\Anaconda3\\lib\\site-packages', 'F:\\py\\Anaconda3\\lib\\site-packages\\win32', 'F:\\py\\Anaconda3\\lib\\site-packages\\win32\\lib', 'F:\\py\\Anaconda3\\lib\\site-packages\\Pythonwin', 'F:\\py\\Anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\那年\\.ipython']


NameError: name 'python3' is not defined

In [3]:
z

NameError: name 'python' is not defined